#!/usr/bin/env python3
"""
Generates the SQL seed for Ria Mukharjee's artwork from the Cloudinary upload results.

Each artwork becomes TWO products, per docs/originals-vs-prints-flows.md:
  * an Original — IsOriginal, StockQuantity 1, no variants
  * a Print     — standard variant matrix (A4 DL / A4 print / A3 print)

IDs are never hardcoded: every insert uses RETURNING so the script is safe to run
against a database that already has products (i.e. production).
"""
import json
from pathlib import Path

CATALOG = json.loads(Path("docs/artwork-catalog-proposal.json").read_text())
UPLOADS = json.loads(Path("cloudinary_artwork_results.json").read_text())
OUT = Path("Infrastructure/Persistence/Seeds/SeedRiaArtwork.sql")

# Placeholder pricing — products are seeded as drafts (IsAvailable FALSE) so nothing
# goes live at a price nobody chose. Print figures reuse the existing template.
ORIGINAL_PRICE = "15000.00"
PRINT_BASE, PRINT_FINAL = "1499.00", "1199.00"
VARIANTS = [
    ("A4 Digital Download", 0, "A4-DL",  "0",   "NULL", "1199.00", "A4"),
    ("A4 Fine Art Print",   1, "A4-PRT", "450", "15",   "1499.00", "A4"),
    ("A3 Fine Art Print",   1, "A3-PRT", "750", "10",   "1999.00", "A3"),
]
# slug -> (Originals sub-category, Prints sub-category)
BUCKETS = {
 "connaught-place":("ARCHITECTURE","CITYSCAPES"), "ganesha-study":("SCULPTURE_STUDIES","BLACK_AND_WHITE"),
 "dancing-deity-relief":("SCULPTURE_STUDIES","BLACK_AND_WHITE"), "lama-art-house":("ARCHITECTURE","CITYSCAPES"),
 "gabled-house-cluster":("ARCHITECTURE","TRAVEL_ART"), "house-among-palms":("ARCHITECTURE","TRAVEL_ART"),
 "four-masks":("SCULPTURE_STUDIES","BLACK_AND_WHITE"), "stilt-house":("ARCHITECTURE","TRAVEL_ART"),
 "festive-storefront":("ARCHITECTURE","CITYSCAPES"), "carved-torana":("SCULPTURE_STUDIES","BLACK_AND_WHITE"),
 "flower-stall":("ARCHITECTURE","CITYSCAPES"), "caparisoned-elephant":("SCULPTURE_STUDIES","TRAVEL_ART"),
 "deity-on-bull":("SCULPTURE_STUDIES","BLACK_AND_WHITE"), "temple-gopuram":("ARCHITECTURE","TRAVEL_ART"),
 "carved-doorway":("SCULPTURE_STUDIES","BLACK_AND_WHITE"), "village-among-palms":("ARCHITECTURE","TRAVEL_ART"),
 "hill-town-rooftops":("ARCHITECTURE","CITYSCAPES"), "verandah-bungalow":("ARCHITECTURE","TRAVEL_ART"),
 "longhouse-palms":("ARCHITECTURE","TRAVEL_ART"), "timber-house-stairs":("ARCHITECTURE","TRAVEL_ART"),
 "brass-shop":("ARCHITECTURE","CITYSCAPES"), "ganesha-stele":("SCULPTURE_STUDIES","BLACK_AND_WHITE"),
 "blue-relief":("SCULPTURE_STUDIES","TRAVEL_ART"), "apsara":("SCULPTURE_STUDIES","BLACK_AND_WHITE"),
 "domed-monument":("ARCHITECTURE","CITYSCAPES"),
}

by_slug = {}
for u in UPLOADS:
    base = u["public_id_requested"]
    slug = base.rsplit("-", 1)[0] if u["role"] == "alt" else base
    by_slug.setdefault(slug, []).append(u)

def q(s):
    return "'" + str(s).replace("'", "''") + "'"

L = [
 "-- Seed: Ria Mukharjee's artwork catalogue (25 pieces x Original + Print).",
 "-- Generated by generate_artwork_seed.py from cloudinary_artwork_results.json.",
 "--",
 "-- Seeded as DRAFTS (IsAvailable = FALSE). Prices are placeholders: set real prices",
 "-- in the admin portal and flip availability when each piece is ready to sell.",
 "-- Physical dimensions are left NULL rather than guessed.",
 "",
 "BEGIN;",
 "",
 "-- Sub-categories for Originals (Commissions was the only existing one and doesn't fit).",
 "INSERT INTO ProductSubCategories (CategoryId, NameCode, Name, PrintName, Description, IsActive, Slug)",
 "SELECT c.Id, v.namecode, v.name, v.name, v.descr, TRUE, v.slug",
 "FROM ProductCategories c",
 "JOIN (VALUES",
 "    ('ARCHITECTURE', 'Architecture', 'Buildings, streets and facades drawn from life.', 'architecture'),",
 "    ('SCULPTURE_STUDIES', 'Sculpture Studies', 'Carvings, reliefs and temple sculpture.', 'sculpture-studies')",
 ") AS v(namecode, name, descr, slug) ON TRUE",
 "WHERE c.NameCode = 'ORIGINALS'",
 "  AND NOT EXISTS (SELECT 1 FROM ProductSubCategories s WHERE s.NameCode = v.namecode);",
 "",
 "DO $$",
 "DECLARE",
 "    artist_id INT;",
 "    pid       INT;",
 "    vid       INT;",
 "    img_id    INT;",
 "BEGIN",
 "    -- Match by name rather than taking the first row: on a database where the artist",
 "    -- profile has not been renamed yet this must fail loudly, not silently credit",
 "    -- 50 new products to the wrong person.",
 "    SELECT Id INTO artist_id FROM ArtistProfiles WHERE DisplayName = 'Ria Mukharjee';",
 "    IF artist_id IS NULL THEN",
 "        RAISE EXCEPTION 'No ArtistProfiles row with DisplayName = ''Ria Mukharjee'' - update the artist profile before seeding.';",
 "    END IF;",
 "",
]

for n, art in enumerate(CATALOG["artworks"], start=1):
    slug, name = art["slug"], art["name"]
    imgs = by_slug.get(slug, [])
    if not imgs:
        continue
    orig_sub, print_sub = BUCKETS[slug]
    hero = imgs[0]
    seq = f"{n:03d}"
    desc = f"{art['subject']}. {art['medium']}."
    short = art["subject"]

    for kind in ("original", "print"):
        is_orig = kind == "original"
        L += [
        f"    -- [{n:02d}] {name} ({kind})",
        f"    IF NOT EXISTS (SELECT 1 FROM Products WHERE Slug = {q(slug if is_orig else slug + '-print')}"
f" OR ProductId = {q('BIP-RM-ORG-' + seq if is_orig else 'BIP-RM-PRT-' + seq)}) THEN",
        "    INSERT INTO Products (ArtistId, ProductId, Name, Slug, NameCode, PrintName, Description,",
        "        ShortDescription, BasePrice, FinalPrice, CurrencyCode, CategoryId, SubCategoryId,",
        "        IsFeatured, IsAvailable, CoverImageUrl, HeaderImageUrl, StockQuantity,",
        "        CreatedBy, UpdatedBy, IsUsingStandardVariants)",
        f"    VALUES (artist_id, {q('BIP-RM-ORG-' + seq if is_orig else 'BIP-RM-PRT-' + seq)}, "
        f"{q(name if is_orig else name + ' (Print)')}, {q(slug if is_orig else slug + '-print')},",
        f"        {q(slug.upper().replace('-', '_') + ('' if is_orig else '_PRINT'))}, {q(name)}, {q(desc)}, {q(short)},",
        f"        {ORIGINAL_PRICE if is_orig else PRINT_BASE}, {ORIGINAL_PRICE if is_orig else PRINT_FINAL}, 'INR',",
        f"        (SELECT Id FROM ProductCategories WHERE NameCode = {q('ORIGINALS' if is_orig else 'PRINTS')}),",
        f"        (SELECT Id FROM ProductSubCategories WHERE NameCode = {q(orig_sub if is_orig else print_sub)}),",
        f"        FALSE, FALSE, {q(hero['secure_url'])}, {q(hero['secure_url'])}, "
        f"{'1' if is_orig else 'NULL'}, 'seed', 'seed', {'FALSE' if is_orig else 'TRUE'})",
        "    RETURNING Id INTO pid;",
        "",
        "    INSERT INTO ArtSpecifications (ProductId, Unit, Material, FileFormat, ResolutionDpi,",
        "        PixelDimensions, PaperType, InkType, IsOriginal, IsSigned, HasCertificate, FramingStatus)",
        f"    VALUES (pid, 'cm', {q(art['medium'])}, {q(hero['format'].upper())}, 300,",
        f"        {q(str(hero['width']) + 'x' + str(hero['height']))}, "
        f"{q('Paper') if is_orig else 'NULL'}, {q(art['medium'])},",
        f"        {'TRUE' if is_orig else 'FALSE'}, FALSE, FALSE, 'Unframed');",
        "",
        ]
        for order, im in enumerate(imgs):
            L += [
            "    INSERT INTO ProductImages (ProductId, AltText, IsPrimary, DisplayOrder, PublicId,",
            "        BaseUrl, AspectRatio, Width, Height, Format, FileSize)",
            f"    VALUES (pid, {q(name)}, {'TRUE' if order == 0 else 'FALSE'}, {order}, {q(im['public_id'])},",
            f"        {q(im['secure_url'])}, {round(im['width'] / im['height'], 4)}, {im['width']}, {im['height']},",
            f"        {q(im['format'])}, {im['bytes']});",
            ]
        L.append("")
        if not is_orig:
            for label, fulfil, sku, wt, stock, price, opt in VARIANTS:
                L += [
                "    INSERT INTO ProductVariants (ProductId, Label, FulfillmentType, Sku, WeightGrams,",
                "        StockQuantity, AbsolutePrice)",
                f"    VALUES (pid, {q(label)}, {fulfil}, {q('BIP-RM-PRT-' + seq + '-' + sku)}, {wt}, {stock}, {price})",
                "    RETURNING Id INTO vid;",
                "    INSERT INTO ProductVariantOptions (ProductVariantId, Value, PriceModifier, AbsolutePrice, StockQuantity)",
                f"    VALUES (vid, {q(opt)}, 0.00, {price}, {stock});",
                ]
            L.append("")
        L += ["    END IF;", ""]

L += ["END $$;", "", "COMMIT;", ""]
OUT.write_text("\n".join(L))
print(f"wrote {OUT} ({len(L)} lines)")
print(f"artworks: {len(CATALOG['artworks'])}  products: {len(CATALOG['artworks'])*2}  images: {len(UPLOADS)}")
