#!/usr/bin/env python3
"""
Reads cloudinary_upload_results.json and generates a SQL seed file
for Products and ProductImages matching the BlackInkPaper schema.
"""

import json
import re
import sys
from pathlib import Path

RESULTS_FILE = Path("cloudinary_upload_results.json")
OUTPUT_FILE = Path("Infrastructure/Persistence/Seeds/SeedIllustrationProducts.sql")

# Seed defaults — adjust as needed
ARTIST_ID = 1
CATEGORY_ID = 1          # Wall Art
SUBCATEGORY_ID = 1       # Abstract
BASE_PRICE = 1499.00
FINAL_PRICE = 1199.00
CURRENCY = "INR"
CREATED_BY = "seed"

# Standard variant IDs (from existing seed)
# Size: id=1 (options: A4=1, A3=2), Format: id=2 (Digital Download=3, Fine Art Print=4)
VARIANT_TEMPLATES = [
    {"label": "A4 Digital Download", "fulfillment": 0, "sku_suffix": "A4-DL",  "weight": 0,   "stock": None, "price": 1199.00},
    {"label": "A4 Fine Art Print",   "fulfillment": 1, "sku_suffix": "A4-PRT", "weight": 450,  "stock": 15,   "price": 1499.00},
    {"label": "A3 Fine Art Print",   "fulfillment": 1, "sku_suffix": "A3-PRT", "weight": 750,  "stock": 10,   "price": 1999.00},
]


def slugify(text: str) -> str:
    text = text.lower()
    text = re.sub(r"[^\w\s-]", "", text)
    text = re.sub(r"[\s_]+", "-", text)
    return text.strip("-")


def name_from_public_id(public_id: str) -> str:
    """Turn 'illustrations/asset_10' → 'Illustration 10'"""
    base = public_id.split("/")[-1]                  # asset_10
    base = re.sub(r"^asset_", "Illustration ", base) # Illustration 10
    base = re.sub(r"screenshot_.*", "Photo Reference", base)
    return base.title()


def sku_prefix(product_id_str: str) -> str:
    """BIP-ILL-010 → ILL010"""
    num = product_id_str.split("-")[-1]
    return f"ILL{num}"


def main():
    if not RESULTS_FILE.exists():
        print(f"ERROR: {RESULTS_FILE} not found. Run upload_illustrations.sh first.")
        sys.exit(1)

    with open(RESULTS_FILE) as f:
        uploads = json.load(f)

    if not uploads:
        print("No upload results found.")
        sys.exit(1)

    print(f"Generating seed SQL for {len(uploads)} assets...")

    lines = [
        "-- Auto-generated seed: Illustration products from Cloudinary uploads",
        "-- Generated by generate_seed_from_cloudinary.py",
        "",
        "BEGIN;",
        "",
    ]

    # Track the next IDs (DB currently has products 1,2,3 and variants 1-4)
    product_start_id = 4
    variant_start_id = 5      # existing seed has 4 variants
    variant_opt_start_id = 5  # existing seed has 4 options
    image_start_id = 1

    product_rows = []
    art_spec_rows = []
    variant_rows = []
    variant_opt_rows = []
    image_rows = []
    tag_map_rows = []

    for idx, asset in enumerate(uploads):
        pub_id: str = asset.get("public_id", "")
        secure_url: str = asset.get("secure_url", "")
        width: int = asset.get("width", 0)
        height: int = asset.get("height", 0)
        fmt: str = asset.get("format", "svg")
        file_bytes: int = asset.get("bytes", 0)
        is_screenshot = "screenshot" in pub_id.lower()

        db_id = product_start_id + idx
        seq_num = f"{db_id:03d}"
        product_code = f"BIP-ILL-{seq_num}"
        name = name_from_public_id(pub_id)
        slug = slugify(name)
        name_code = slug.upper().replace("-", "_")
        aspect = round(width / height, 4) if height else 1.0
        base_url = secure_url  # use as cover + header

        product_rows.append(
            f"({db_id}, {ARTIST_ID}, '{product_code}', '{name}', '{slug}', "
            f"'{name_code}', '{name}', "
            f"'Original illustration available as digital download or fine art print.', "
            f"'Art print from the BlackInk Paper collection.', "
            f"{BASE_PRICE}, {FINAL_PRICE}, '{CURRENCY}', "
            f"{CATEGORY_ID}, {SUBCATEGORY_ID}, FALSE, TRUE, "
            f"'{secure_url}', '{secure_url}', "
            f"0.0, 0, NULL, CURRENT_TIMESTAMP, '{CREATED_BY}', CURRENT_TIMESTAMP, '{CREATED_BY}', TRUE)"
        )

        art_spec_rows.append(
            f"({db_id}, NULL, NULL, 'cm', NULL, NULL, NULL, "
            f"'{'SVG' if not is_screenshot else 'PNG'}', 300, "
            f"'{width}x{height}', 'Digital', NULL, NULL, FALSE, FALSE, FALSE, 'Unframed', "
            f"CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)"
        )

        # Variants
        sku_pfx = sku_prefix(product_code)
        for v_idx, tmpl in enumerate(VARIANT_TEMPLATES):
            v_id = variant_start_id
            variant_start_id += 1  # noqa — intentional counter bump
            stock = "NULL" if tmpl["stock"] is None else str(tmpl["stock"])
            variant_rows.append(
                f"({v_id}, {db_id}, '{tmpl['label']}', {tmpl['fulfillment']}, "
                f"'{sku_pfx}-{tmpl['sku_suffix']}', {tmpl['weight']}, {stock}, {tmpl['price']})"
            )

            opt_id = variant_opt_start_id
            variant_opt_start_id += 1
            opt_value = tmpl["label"].split(" ")[0]  # "A4", "A3"
            variant_opt_rows.append(
                f"({opt_id}, {v_id}, '{opt_value}', 0.00, {tmpl['price']}, {stock})"
            )

        # ProductImage (primary)
        image_rows.append(
            f"({image_start_id}, {db_id}, '{name} - Primary', TRUE, 1, "
            f"'{pub_id}', '{secure_url}', "
            f"{aspect}, {width}, {height}, NULL, '{fmt}', 300, {file_bytes})"
        )
        image_start_id += 1

        # Tag: New Arrival (id=3)
        tag_map_rows.append(f"({db_id}, 3)")

    # Write INSERT blocks
    lines += [
        "-- Products",
        "INSERT INTO Products",
        "(Id, ArtistId, ProductId, Name, Slug, NameCode, PrintName, Description, ShortDescription,",
        " BasePrice, FinalPrice, CurrencyCode, CategoryId, SubCategoryId, IsFeatured, IsAvailable,",
        " CoverImageUrl, HeaderImageUrl, AverageRating, ReviewCount, StockQuantity,",
        " CreatedAt, CreatedBy, UpdatedAt, UpdatedBy, IsUsingStandardVariants)",
        "OVERRIDING SYSTEM VALUE",
        "VALUES",
        ",\n".join(product_rows) + ";",
        "",
        "-- ArtSpecifications",
        "INSERT INTO ArtSpecifications",
        "(ProductId, Width, Height, Unit, WeightGrams, IsFramed, Material, FileFormat, ResolutionDpi,",
        " PixelDimensions, PaperType, PaperWeight, InkType, IsOriginal, IsSigned, HasCertificate,",
        " FramingStatus, CreatedAt, UpdatedAt)",
        "VALUES",
        ",\n".join(art_spec_rows) + ";",
        "",
        "-- ProductVariants",
        "INSERT INTO ProductVariants",
        "(Id, ProductId, Label, FulfillmentType, Sku, WeightGrams, StockQuantity, AbsolutePrice)",
        "OVERRIDING SYSTEM VALUE",
        "VALUES",
        ",\n".join(variant_rows) + ";",
        "",
        "-- ProductVariantOptions",
        "INSERT INTO ProductVariantOptions",
        "(Id, ProductVariantId, Value, PriceModifier, AbsolutePrice, StockQuantity)",
        "OVERRIDING SYSTEM VALUE",
        "VALUES",
        ",\n".join(variant_opt_rows) + ";",
        "",
        "-- ProductImages",
        "INSERT INTO ProductImages",
        "(Id, ProductId, AltText, IsPrimary, DisplayOrder, PublicId, BaseUrl, AspectRatio,",
        " Width, Height, PlaceholderUrl, Format, Dpi, FileSize)",
        "OVERRIDING SYSTEM VALUE",
        "VALUES",
        ",\n".join(image_rows) + ";",
        "",
        "-- Map_ProductTags (New Arrival)",
        "INSERT INTO Map_ProductTags (ProductId, TagId) VALUES",
        ",\n".join(tag_map_rows) + ";",
        "",
        "-- Sync sequences",
        "SELECT setval(pg_get_serial_sequence('Products', 'id'), COALESCE(MAX(id), 1)) FROM Products;",
        "SELECT setval(pg_get_serial_sequence('ProductVariants', 'id'), COALESCE(MAX(id), 1)) FROM ProductVariants;",
        "SELECT setval(pg_get_serial_sequence('ProductVariantOptions', 'id'), COALESCE(MAX(id), 1)) FROM ProductVariantOptions;",
        "SELECT setval(pg_get_serial_sequence('ProductImages', 'id'), COALESCE(MAX(id), 1)) FROM ProductImages;",
        "",
        "COMMIT;",
    ]

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text("\n".join(lines))
    print(f"Seed SQL written to: {OUTPUT_FILE}")
    print(f"  {len(product_rows)} products")
    print(f"  {len(variant_rows)} variants")
    print(f"  {len(image_rows)} product images")


if __name__ == "__main__":
    main()
