using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.DependencyInjection;

namespace Infrastructure.Persistence.Seeding;

/// <summary>
/// Creates roles and the default accounts. Goes through UserManager rather than SQL so
/// password hashes and security stamps are generated by Identity itself.
/// </summary>
internal static class IdentitySeeder
{
    private const string ArtistUserId = "user-artist";   // referenced by ArtistProfiles.UserId in the SQL seeds
    private static readonly string[] Roles = ["Admin", "Artist", "User"];

    private sealed record SeedUser(string Email, string Password, string FullName, string Role, string? Id = null);

    private static readonly SeedUser[] Users =
    [
        new("admin@admin.com", "Admin@123!", "System Administrator", "Admin"),
        new("artist@artist.com", "Artist@123!", "Ria Mukharjee", "Artist", ArtistUserId),
    ];

    public static async Task SeedAsync(IServiceProvider services)
    {
        var roleManager = services.GetRequiredService<RoleManager<IdentityRole>>();
        var userManager = services.GetRequiredService<UserManager<AppIdentityUser>>();

        foreach (var role in Roles)
        {
            if (!await roleManager.RoleExistsAsync(role))
                await roleManager.CreateAsync(new IdentityRole(role));
        }

        foreach (var seed in Users)
        {
            var existing = await userManager.FindByEmailAsync(seed.Email);
            if (existing is not null)
            {
                // Keep the display name current even when the account predates a rename.
                if (existing.FullName != seed.FullName)
                {
                    existing.FullName = seed.FullName;
                    await userManager.UpdateAsync(existing);
                }
                continue;
            }

            var user = new AppIdentityUser
            {
                UserName = seed.Email,
                Email = seed.Email,
                FullName = seed.FullName,
                EmailConfirmed = true,
            };
            if (seed.Id is not null) user.Id = seed.Id;

            var result = await userManager.CreateAsync(user, seed.Password);
            if (!result.Succeeded)
            {
                var errors = string.Join("; ", result.Errors.Select(e => e.Description));
                throw new InvalidOperationException($"Could not create seed user {seed.Email}: {errors}");
            }

            await userManager.AddToRoleAsync(user, seed.Role);
        }
    }
}
