SET NOCOUNT ON;

PRINT 'Checking primary-key auto-generation strategy...';

DECLARE @PrimaryKeyChecks TABLE
(
    TableName SYSNAME NOT NULL,
    IdColumn SYSNAME NOT NULL
);

INSERT INTO @PrimaryKeyChecks (TableName, IdColumn)
VALUES
    ('ArtSpecifications', 'Id'),
    ('ArtistProfiles', 'Id'),
    ('AspNetRoleClaims', 'Id'),
    ('AspNetUserClaims', 'Id'),
    ('CartItemSelectedVariants', 'Id'),
    ('CartItems', 'Id'),
    ('Carts', 'Id'),
    ('InventoryTransactions', 'Id'),
    ('OrderItemSelectedVariants', 'Id'),
    ('OrderItems', 'Id'),
    ('Orders', 'Id'),
    ('PaymentWebhookEvents', 'Id'),
    ('ProductCategories', 'Id'),
    ('ProductImages', 'Id'),
    ('ProductStandardVariantOptions', 'Id'),
    ('ProductStandardVariants', 'Id'),
    ('ProductSubCategories', 'Id'),
    ('ProductTags', 'Id'),
    ('ProductVariantOptions', 'Id'),
    ('ProductVariants', 'Id'),
    ('Products', 'Id'),
    ('ShippingAddresses', 'Id');

DECLARE @TableName SYSNAME;
DECLARE @IdColumn SYSNAME;
DECLARE @ObjectId INT;
DECLARE @ColumnId INT;
DECLARE @IsIdentity BIT;

DECLARE pk_cursor CURSOR LOCAL FAST_FORWARD FOR
SELECT TableName, IdColumn
FROM @PrimaryKeyChecks
ORDER BY TableName;

OPEN pk_cursor;
FETCH NEXT FROM pk_cursor INTO @TableName, @IdColumn;

WHILE @@FETCH_STATUS = 0
BEGIN
    SET @ObjectId = OBJECT_ID(N'dbo.' + @TableName, N'U');

    IF @ObjectId IS NULL
    BEGIN
        PRINT 'SKIP: dbo.' + @TableName + ' does not exist.';
        FETCH NEXT FROM pk_cursor INTO @TableName, @IdColumn;
        CONTINUE;
    END

    SELECT @ColumnId = c.column_id
    FROM sys.columns c
    WHERE c.object_id = @ObjectId
      AND c.name = @IdColumn;

    IF @ColumnId IS NULL
    BEGIN
        PRINT 'SKIP: dbo.' + @TableName + '.' + @IdColumn + ' does not exist.';
        FETCH NEXT FROM pk_cursor INTO @TableName, @IdColumn;
        CONTINUE;
    END

    SET @IsIdentity = COLUMNPROPERTY(@ObjectId, @IdColumn, 'IsIdentity');

    IF @IsIdentity = 1
    BEGIN
        PRINT 'OK: dbo.' + @TableName + '.' + @IdColumn + ' already auto-generates via IDENTITY.';
    END
    ELSE
    BEGIN
        PRINT 'ACTION REQUIRED: dbo.' + @TableName + '.' + @IdColumn + ' is not IDENTITY.';
        PRINT 'SQL Server cannot ALTER an existing column to add IDENTITY.';
        PRINT 'Migration pattern for dbo.' + @TableName + ':';
        PRINT '  1. Create a replacement table with ' + @IdColumn + ' INT IDENTITY(1,1).';
        PRINT '  2. Copy data with SET IDENTITY_INSERT dbo.' + @TableName + '_New ON/OFF if values must be preserved.';
        PRINT '  3. Recreate PKs, FKs, indexes, and defaults.';
        PRINT '  4. Swap table names inside a transaction.';
    END

    FETCH NEXT FROM pk_cursor INTO @TableName, @IdColumn;
END

CLOSE pk_cursor;
DEALLOCATE pk_cursor;

PRINT '---';
PRINT 'Tables intentionally excluded from automatic integer identity handling:';
PRINT '  dbo.Users: ASP.NET Identity string key, generated by the application.';
PRINT '  dbo.Roles: ASP.NET Identity string key, generated by the application.';
PRINT '  dbo.TokenBlacklist: string primary key (TokenId), not an integer identity candidate.';
PRINT '  dbo.Map_ProductTags: composite key, not a single-column identity candidate.';
PRINT '  dbo.AspNetUserLogins: composite key, not a single-column identity candidate.';
PRINT '  dbo.AspNetUserRoles: composite key, not a single-column identity candidate.';
PRINT '  dbo.AspNetUserTokens: composite key, not a single-column identity candidate.';
PRINT '  dbo.__EFMigrationsHistory: string primary key, managed by EF Core.';
