:setvar SeedRoot .

PRINT 'Running seed scripts from $(SeedRoot)';

:r $(SeedRoot)\00_ClearTables.sql
:r $(SeedRoot)\10_SeedIdentity.sql
:r $(SeedRoot)\20_SeedCatalog.sql
:r $(SeedRoot)\30_SeedCommerce.sql
:r $(SeedRoot)\40_EnsureAutoGeneratedPrimaryKeys.sql

PRINT 'All seed scripts completed.';
